#!/bin/bash

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

REPO="docker-tomcat"

# Uncomment to set default mount points
# HOST_MOUNT="$PWD/build/libs/"
# CONTAINER_MOUNT="/opt/apache-tomcat/webapps/"

# Default host:container port
HOST_PORT="80"
CONTAINER_PORT="8080"

setup() {
    if [[ -z "$MOUNT" && -n "$HOST_MOUNT" && -n "$CONTAINER_MOUNT" ]]; then
        MOUNT="-v $HOST_MOUNT:$CONTAINER_MOUNT"
    fi

    if [[ -z "$PORT" && -n "$HOST_PORT" && -n "$CONTAINER_PORT" ]]; then
        PORT="-p $HOST_PORT:$CONTAINER_PORT"
    fi
}

build() {
    setup
    docker build --rm -t $REPO $SCRIPT_DIR
}

run() {
    setup
    docker run --rm $PORT $MOUNT -i -t $REPO
}

cleanup() {
    # Remove stopped containers
    CONTAINERS=$(docker ps  -a | grep 'Exit' | awk '{print $1}')
    if [[ -n $CONTAINERS ]]; then
        docker rm $CONTAINERS
    fi

    # Remove untagged images
    IMAGES=$(docker images | grep "^<none>" | awk '{print $3}')
    if [[ -n $IMAGES ]]; then
        docker rmi $IMAGES
    fi
}

remove() {
    IMAGE=$(docker images | grep $REPO | awk '{print $3}')
    if [[ -n $IMAGE ]]; then
        docker rmi $IMAGE
    fi
}

usage() {
    echo "Usage: $0 [build | [-v hostMount:containerMount] [-p hostPort:containerPort] run | cleanup | remove]"
}

if [[ $# == 0 ]];then
    usage
    exit 1
fi

MOUNT=""
PORT=""
while [[ -n "$1" ]]; do
    case $1 in
        -v ) shift
            MOUNT="-v $1"
            ;;
        -p ) shift
            PORT="-p $1"
            ;;
        build ) build
            ;;
        run ) run
            ;;
        cleanup ) cleanup
            ;;
        remove ) remove
            ;;
        * ) usage
            exit 1
            ;;
    esac
    shift
done
