# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.provider "docker" do |d|
        d.build_dir = "."
        d.create_args = ["-p", "80:8080"]
        d.remains_running = true
        d.vagrant_vagrantfile = "../Vagrantfile"
    end

end
